/*
 * generated by Xtext 2.9.0.rc1
 */
package org.xtext.cnp.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/cnp/mydsl/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
