/*
 * generated by Xtext 2.9.0.rc1
 */
package org.xtext.cnp.mydsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
