/*
 * generated by Xtext 2.9.0.rc1
 */
package org.xtext.cnp.mydsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MyDslUiModule extends AbstractMyDslUiModule {
}
