/*
 * generated by Xtext 2.9.0.rc1
 */
package org.xtext.cnp.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
